# Generated by Django 3.1.1 on 2020-09-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('done', models.BooleanField()),
                ('created', models.DateField()),
                ('bucket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.bucket')),
            ],
        ),
    ]
